import { Head } from "next/document";
import "./styles.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/assets/icon.ico" />
        <meta property="og:type" content="website" />
        ...
      </Head>
      <body>{children}</body>
    </html>
  )
}
